### ISSUE TITLE
PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption', 'text'] in ['__key__', '__url__', 'mp4']")

### ISSUE THREAD

**Issue by AdvancedHe** [yhZhai/mcm#7]
Hi, when I start to train, it appeared this:
![image](https://github.com/user-attachments/assets/3aa45e19-74e6-4288-ad31-ea1f2ecbe137)
![image](https://github.com/user-attachments/assets/a4ca8d0a-9b44-4fee-8c98-298303af3b9a)

```
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['mp4', 'avi', 'mov', 'mkv'
] in ['__key__', '__url__', 'json']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['mp4', 'avi', 'mov', 'mkv'
] in ['__key__', '__url__', 'json']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['mp4', 'avi', 'mov', 'mkv'
] in ['__key__', '__url__', 'json']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['mp4', 'avi', 'mov', 'mkv'
] in ['__key__', '__url__', 'json']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
Steps:   0%|                                                                                                                              | 0/154212 [00:00<?, ?it/s]
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['json', 'txt', 'caption',
'text'] in ['__key__', '__url__', 'mp4']")
  warnings.warn(repr(exn))
/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/webdataset/handlers.py:34: UserWarning: ValueError("didn't find ['mp4', 'avi', 'mov', 'mkv'
] in ['__key__', '__url__', 'json']")

```

It stays on this interface for a long time and does not update the training status.
Is it normal? If not, what's wrong with it and how do I solve this problem?
Thanks a lot!

**Comment by yhZhai** [comment]
Hi there, thank you for your interest in our work!

Unfortunately, I did not encounter this problem before. I found [this issue](https://github.com/huan085128/lcm_lora/issues/1)  in LCM, could you please take a try and see if it could help resolve this problem?

**Comment by AdvancedHe** [comment]
Yes, I solve this problem from this link, thanks a lot.
In conclusion, to train with own dataset:

- Make mp4 files and json file sorted, for example: video_00001.mp4,  video_00001.json ...
- Compress them as tar file

By the way,  I want to ask how to inference with my own weight, what I should edit in the `demo.py` ?
Thanks a lot!

**Comment by AdvancedHe** [comment]
I modify model_id in `def get_modelscope_pipeline()` :
```
def get_modelscope_pipeline():
    # model_id = "ali-vilab/text-to-video-ms-1.7b"
    model_id = "work_dirs/modelscopet2v_distillation/checkpoint-54000"
    pipe = DiffusionPipeline.from_pretrained(
        model_id, torch_dtype=torch.float16, variant="fp16"
    )
    scheduler = LCMScheduler.from_pretrained(
        model_id,
        subfolder="scheduler",
        timestep_scaling=4.0,
    )
    pipe.scheduler = scheduler
    pipe.enable_vae_slicing()

    return pipe
```
But it appears:
```
Traceback (most recent call last):
  File "/group/ossdphi_algo_scratch_01/hecui102/codelib/helps/mcm/mcm/demo.py", line 120, in <module>
    main()
  File "/group/ossdphi_algo_scratch_01/hecui102/codelib/helps/mcm/mcm/demo.py", line 32, in main
    pipeline = get_modelscope_pipeline()
  File "/group/ossdphi_algo_scratch_01/hecui102/codelib/helps/mcm/mcm/demo.py", line 105, in get_modelscope_pipeline
    pipe = DiffusionPipeline.from_pretrained(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 723, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 377, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory work_dirs/modelscopet2v_distillation/checkpoint-54000.Traceback (most recent call last):
  File "/group/ossdphi_algo_scratch_01/hecui102/codelib/helps/mcm/mcm/demo.py", line 120, in <module>
    main()
  File "/group/ossdphi_algo_scratch_01/hecui102/codelib/helps/mcm/mcm/demo.py", line 32, in main
    pipeline = get_modelscope_pipeline()
  File "/group/ossdphi_algo_scratch_01/hecui102/codelib/helps/mcm/mcm/demo.py", line 105, in get_modelscope_pipeline
    pipe = DiffusionPipeline.from_pretrained(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 723, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/mcm/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 377, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory work_dirs/modelscopet2v_distillation/checkpoint-54000.
```

**Comment by yhZhai** [comment]
Thank you for providing the solution!

To use your custom models for inference, please only replace [this call](https://github.com/yhZhai/mcm/blob/d210332490cfbcb6bc9c71a57dd1091907e5b16d/demo.py#L31), from

```
    lora = PeftModel.from_pretrained(
        pipeline.unet,
        model_id,
        subfolder=model_path,
        adapter_name="pretrained_lora",
        torch_device="cpu",
    )
```

to

```
    lora = PeftModel.from_pretrained(
        pipeline.unet,
        "work_dirs/modelscopet2v_distillation/checkpoint-54000",
        adapter_name="pretrained_lora",
        torch_device="cpu",
    )
```

**Comment by AdvancedHe** [comment]
Thanks a lot! I follow your code and inference successfully.
Next I will use mcm to accelerate my own t2v model.
Regards.
